sudo: required
services:
- docker
before_install:
- docker build -t denysisaievsbtech/react-test -f ./client/Dockerfile.dev ./client
script:
- docker run denysisaievsbtech/react-test npm run test -- --coverage
after_succes:
- docker build -t denysisaievsbtech/multi-client ./client
- docker build -t denysisaievsbtech/multi-nginx ./nginx
- docker build -t denysisaievsbtech/multi-server ./server
- docker build -t denysisaievsbtech/multi-worker ./worker
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
- docker push denysisaievsbtech/multi-client
- docker push denysisaievsbtech/multi-nginx
- docker push denysisaievsbtech/multi-server
- docker push denysisaievsbtech/multi-worker
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAYNTAELUMRSZK4RKR
  secret_access_key:
    secure: SJmVg3BThdhw6ismu6JIkqBKYpXM2sTzWuHLgqytbHOCKI0Qn4UFrh2IFXJKszYmIgDfSNgFDQ4mn8dTToNIVFYmXQd3D98APncF/zMYrU2lnfsvnWuBzEqSRpX5l2ccfkVAH8Y8seAdqQk9m79uYT7jvwWNvlJttAh/iNYIptYlk40avdpuvNnFbpDm+UWdW0sZYP/vofhVgVAfWmNNzXSMaZiDMG3c6pwuV4stQrVszHuXQrowXwugLa6/0DzWlHgjSSQxftbZY/0bEbhbRQlrLmuWriH7nNawInRPJl4M3eUP0NG9PDR8PqAaOQkgKbqmlfaKuFIoR4GOY9ugN7zgbUYyUJ/w8TGEAdhN3FFgBV5eIWEHGC5lrZf/VVPm3oTCDrj3cGp200/QO9dhAud2wHEphERSjqo7QBEZEbjisv6X5hDYU5V2W2elEox0RC7taaoLCK4HKrhaeqdWoe7wmBohO51t73aOZy7b3uV3YCk1M1F+x86PwvUcQRzst+YWSGvTzA14tBxNjbWS1eibb6tNQnC/WiEHCbbcgAMYS5z0tPwLEy7CSzlDPWsC8D6xSgIT1HLzGX96VJsohny/z7wT3D1qK9nbRPCIAUGvSJaO35vkkGOV4pjXAg++JBlRxehm/yYYxmQzkEonnRwnUR3cqiFDWJ3lKZRa8wY=
  region: us-east-2
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-2-578948455705
  on:
    branch: master
  skip_cleanup: 'true'
